Revert "Update launcher to be usable in GraalVM as well"
* This reverts commit 64184cb52aec36deb3b011f40faed50dbff8d9d7.

diff --git a/bin/truffleruby b/bin/truffleruby
--- a/bin/truffleruby
+++ b/bin/truffleruby
@@ -16,6 +16,18 @@ if [ -n "$RUBY_BIN" ]; then
     exec "$RUBY_BIN" "$@"
 fi
 
+function mtime {
+    uname_str=$(uname)
+    if [ "$uname_str" = 'Linux' ] || [ "$uname_str" = 'SunOS' ]; then
+        stat -c '%Y' "$1" 2>/dev/null || echo 0
+    elif [ "$uname_str" = 'Darwin' ]; then
+        stat -f '%m' "$1" 2>/dev/null || echo 0
+    else
+        echo "unknown platform $uname_str" 1>&2
+        exit 1
+    fi
+}
+
 # get the absolute path of the executable and resolve symlinks
 SELF_PATH=$(cd "$(dirname "$0")" && pwd -P)/$(basename "$0")
 while [ -h "$SELF_PATH" ]; do
@@ -27,70 +39,44 @@ while [ -h "$SELF_PATH" ]; do
     SYM=$(readlink "$SELF_PATH")
     SELF_PATH=$(cd "$DIR" && cd "$(dirname "$SYM")" && pwd)/$(basename "$SYM")
 done
-
-# this is graalvm/language/ruby on graalvm
 root=$(dirname "$(dirname "$SELF_PATH")")
 
-root_parent=$(dirname "$root")
-if [ $(basename "$root") = ruby ] && [ $(basename "$root_parent") = language ]; then
-    on_graalvm=true
-else
-    on_graalvm=false
-fi
+mx_jar="$root/mxbuild/dists/ruby.jar"
+mvn_jar="$root/lib/truffleruby.jar"
+mx_time=$(mtime "$mx_jar")
+mvn_time=$(mtime "$mvn_jar")
 
 if [ -z "$JAVACMD" ]; then
-    if [ -z "$JAVA_HOME" ]; then
-        JAVACMD='java'
-    else
-        JAVACMD="$JAVA_HOME/bin/java"
-    fi
+  if [ -z "$JAVA_HOME" ]; then
+    JAVACMD='java'
+  else
+    JAVACMD="$JAVA_HOME/bin/java"
+  fi
 fi
 
 declare -a java_args
 declare -a ruby_args
 
+print_command=""
 CP=""
-boot_cp_jar=""
+boot_cp_jar="$mvn_jar"
 
-if [ $on_graalvm = false ]; then
-
-    function mtime {
-        uname_str=$(uname)
-        if [ "$uname_str" = 'Linux' ] || [ "$uname_str" = 'SunOS' ]; then
-            stat -c '%Y' "$1" 2>/dev/null || echo 0
-        elif [ "$uname_str" = 'Darwin' ]; then
-            stat -f '%m' "$1" 2>/dev/null || echo 0
-        else
-            echo "unknown platform $uname_str" 1>&2
-            exit 1
-        fi
-    }
-
-    mx_jar="$root/mxbuild/dists/ruby.jar"
-    mvn_jar="$root/lib/truffleruby.jar"
-    mx_time=$(mtime "$mx_jar")
-    mvn_time=$(mtime "$mvn_jar")
-    print_command=""
-    boot_cp_jar="$mvn_jar"
-
-    if [ "$mx_time" -gt "$mvn_time" ]; then
-        # This hash is Truffle's JLINE sha1
-        CP="$CP:$HOME/.mx/cache/JLINE_9504d5e2da5d78237239c5226e8200ec21182040.jar"
-        binary_truffle_dist="$root/mx.imports/binary/truffle/mxbuild/dists"
-        source_truffle_dist="$(dirname "$root")/truffle/mxbuild/dists"
-        if [ -f "$binary_truffle_dist/truffle-api.jar" ]; then # Binary Truffle suite
-            boot_cp_jar="$binary_truffle_dist/truffle-api.jar"
-            CP="$CP:$binary_truffle_dist/truffle-debug.jar"
-        elif [ -f "$source_truffle_dist/truffle-api.jar" ]; then # Source Truffle suite
-            boot_cp_jar="$source_truffle_dist/truffle-api.jar"
-            CP="$CP:$source_truffle_dist/truffle-debug.jar"
-        else
-            echo "Could not find Truffle jars" 1>&2
-            exit 1
-        fi
-        CP="$CP:$mx_jar"
+if [ "$mx_time" -gt "$mvn_time" ]; then
+    # This hash is Truffle's JLINE sha1
+    CP="$CP:$HOME/.mx/cache/JLINE_9504d5e2da5d78237239c5226e8200ec21182040.jar"
+    binary_truffle_dist="$root/mx.imports/binary/truffle/mxbuild/dists"
+    source_truffle_dist="$(dirname "$root")/truffle/mxbuild/dists"
+    if [ -f "$binary_truffle_dist/truffle-api.jar" ]; then # Binary Truffle suite
+        boot_cp_jar="$binary_truffle_dist/truffle-api.jar"
+        CP="$CP:$binary_truffle_dist/truffle-debug.jar"
+    elif [ -f "$source_truffle_dist/truffle-api.jar" ]; then # Source Truffle suite
+        boot_cp_jar="$source_truffle_dist/truffle-api.jar"
+        CP="$CP:$source_truffle_dist/truffle-debug.jar"
+    else
+        echo "Could not find Truffle jars" 1>&2
+        exit 1
     fi
-
+    CP="$CP:$mx_jar"
 fi
 
 while [ $# -gt 0 ]
@@ -134,28 +120,7 @@ if [ -n "$CP" ]; then
 fi
 
 declare -a full_command
-if [ $on_graalvm = false ]; then
-    full_command=(
-        "$JAVACMD"
-        $JAVA_OPTS
-        "-Xbootclasspath/a:$boot_cp_jar"
-        "${java_args[@]}"
-        org.truffleruby.Main
-        "-Xhome=$root"
-        "-Xlauncher=$root/bin/truffleruby"
-        "${ruby_args[@]}"
-    )
-else
-    full_command=(
-        $root/../../bin/java -noverify -polyglot
-        $JAVA_OPTS
-        "${java_args[@]}"
-        com.oracle.graalvm.Main
-        org.truffleruby.Main
-        "-Xlauncher=$root/bin/truffleruby"
-        "${ruby_args[@]}"
-    )
-fi
+full_command=("$JAVACMD" $JAVA_OPTS "-Xbootclasspath/a:$boot_cp_jar" "${java_args[@]}" org.truffleruby.Main "-Xhome=$root" "-Xlauncher=$root/bin/truffleruby" "${ruby_args[@]}")
 
 if [ -n "$print_command" ]; then
     echo "$ ${full_command[@]}"
