Support a source Truffle suite in launcher

diff --git a/bin/truffleruby b/bin/truffleruby
--- a/bin/truffleruby
+++ b/bin/truffleruby
@@ -44,9 +44,19 @@ boot_cp_jar="$mvn_jar"
 if [ "$mx_time" -gt "$mvn_time" ]; then
     # This hash is Truffle's JLINE sha1
     CP="$CP:$HOME/.mx/cache/JLINE_9504d5e2da5d78237239c5226e8200ec21182040.jar"
-    CP="$CP:$root/mx.imports/binary/truffle/mxbuild/dists/truffle-debug.jar"
+    binary_truffle_dist="$root/mx.imports/binary/truffle/mxbuild/dists"
+    source_truffle_dist="$(dirname "$root")/truffle/mxbuild/dists"
+    if [ -f "$binary_truffle_dist/truffle-api.jar" ]; then # Binary Truffle suite
+        boot_cp_jar="$binary_truffle_dist/truffle-api.jar"
+        CP="$CP:$binary_truffle_dist/truffle-debug.jar"
+    elif [ -f "$source_truffle_dist/truffle-api.jar" ]; then # Source Truffle suite
+        boot_cp_jar="$source_truffle_dist/truffle-api.jar"
+        CP="$CP:$source_truffle_dist/truffle-debug.jar"
+    else
+        echo "Could not find Truffle jars"
+        exit 1
+    fi
     CP="$CP:$mx_jar"
-    boot_cp_jar="$root/mx.imports/binary/truffle/mxbuild/dists/truffle-api.jar"
 fi
 
 # Split out any -J argument for passing to the JVM.
